name: Run Olist Data Ingestion

on:
  workflow_dispatch: # Vẫn giữ dòng này để bạn có thể bấm chạy test bằng tay khi cần
  schedule:
    - cron: '0 0 * * *' # Lệnh chạy tự động vào 0h00 sáng mỗi ngày (theo giờ UTC)
jobs:
  run-ingestion-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install duckdb==1.5.2 pandas datasets huggingface_hub requests

      - name: Run Python script
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python ingest.py
